### ISSUE TITLE
h5py==3.1.0 breaks the data browser

### ISSUE THREAD

**Issue by wdeacon** [nanophotonics/nplab#129]
In the latest version of h5py it appears self.haschildren() has depreciated and hence the Browser can no longer populate its Treewidget. Rolling back to h5py==2.9.0 results in a successful build that avoids the problem, I assume there is an easy fix for this we just need to read the docs but definitely good to defeat the problem before version 2.9.0 disappears from pip.

**Comment by eoinell** [comment]
I fixed this, see issue 141 https://github.com/nanophotonics/nplab/issues/141
