### ISSUE TITLE
Qt API Errors

### ISSUE THREAD

**Issue by rwb27** [nanophotonics/nplab#15]
Often we get lots of Qt API errors.  How do we fix this?

**Comment by rwb27** [comment]
There's logic in nplab.utils.gui to deal with it - but while it seems to work for now, the errors are annoying!

**Comment by rwb27** [comment]
There's a project called `qtpy` that aims to help here.  Maybe it would get round this issue??

**Comment by wdeacon** [comment]
See pull request #46 (when you get a chance)
