### ISSUE TITLE
Easy command-line data browser

### ISSUE THREAD

**Issue by rwb27** [nanophotonics/nplab#44]
Use argparse or similar so that we can run "python -m nplab --browse-datafile=foo.h5" - and for a bonus mark provide a batch file and associate it with hdf5.

**Comment by rwb27** [comment]
or an OSX equivalent...

**Comment by wdeacon** [comment]
I have created a python/bat file combination which can handle this (located in the nplab.ui,'open_browser_cmd.py/.bat') the bat file can be attached to the h5 file type through windows open with command and it appears to work nicely if a little slow.
