### ISSUE TITLE
seabreeze gui

### ISSUE THREAD

**Issue by hamidohadi** [nanophotonics/nplab#6]
some features in the new gui don't work. For example: manual axes range and saving spectra in particular. Otherwise, very helpful, thanks!

**Comment by asanders** [comment]
These features were added to the GUI without being implemented yet in the actual code. Axes controls have not been added until a decision is made as to whether to stay with matplotlib or move to pyqtgraph, which already has these features. The datafile script in nplab is what enables data saving to a common file. I need to look into using these features to see how to implement saving spectra.

**Comment by rwb27** [comment]
Manual limits now work.  Will need to check saving.

**Comment by rwb27** [comment]
Saving also "works for me", I'll close the issue for now but reopen it if there's a problem.
