### ISSUE TITLE
Lumenera camera can stop high frame exposures when used with Camera_with__Location GUI

### ISSUE THREAD

**Issue by J-Griffo** [nanophotonics/nplab#72]
Seen in Lab 5. Not seen previously. When using Camera_with_Location GUI, maximum possible exposure that could be set was 585.16ms. True if setting via GUI or console. If the exposure directly set via console using camera.exposure=ArbitaryTime before the camera is passed to CWL, this limitation disappears. 

Cause unknown, perhaps a threading issue due to the GUI

**Comment by eoinell** [comment]
same issue as #59? 
The fix seems to be enabling extended exposure through Lumenera's own software first.
