### ISSUE TITLE
Nonetype and int are being compared in nplab/utils/hdf5_browser

### ISSUE THREAD

**Issue by eoinell** [nanophotonics/nplab#88]
When simply running the hdf5 browser code, it generates the error message 
'<' not supported between instances of 'NoneType' and 'int' That could be corrupted
In py3, comparisons of this sort aren't allowed, but None is treated as < all integers in py2. I tried commenting out all the occurrences of '<' in data_renderers.py, however the error message persisted.

**Comment by YagoDel** [comment]
Fixed by 214a60c9fe46102694005f7be53c144bea23b2dc
