### ISSUE TITLE
PyQt4 vs PyQt5

### ISSUE THREAD

**Issue by eoinell** [nanophotonics/nplab#89]
Throughout nplab, qt4 is used as default, and the matplotlib backend is often set to qt4_agg.
Should we be trying to switch to qt5 for the python3 branch?

**Comment by eoinell** [comment]
https://github.com/nanophotonics/nplab/blob/d904fc84c334a56b8d33fdacf0ca20a827196f89/nplab/ui/hdf5_browser.py#L17

https://github.com/nanophotonics/nplab/blob/d904fc84c334a56b8d33fdacf0ca20a827196f89/nplab/ui/data_renderers.py#L9

Maybe I'm conflating the matplotlib backend with pyqt4/5

**Comment by YagoDel** [comment]
There is a way of setting matplotlib to whatever Qt is installed (which is what I did in the commit)
<from matplotlib.backends.qt_compat import is_pyqt5>

However, I tried simply commenting those two lines out, and the test_data_browser.py runs in both Python 2.7 and 3.4 (although I only have PyQt5 in my environment)
So it might actually be that it's not necessary to manually set anything

**Comment by YagoDel** [comment]
Fixed by 378fcf62a83073c68baa70a39eb877fa9f7b7b42
