### ISSUE TITLE
Data doesn't render in python2

### ISSUE THREAD

**Issue by eoinell** [nanophotonics/nplab#91]
the H5browser pops up for test.h5, however no data is rendered. It works perfectly for python 3.

**Comment by YagoDel** [comment]
Questions:
- This is running tests/test_data_browser.py? 
- Are you running PyQt4 or 5 in each of the environments?
- Is it showing the Tree, but not rendering the data?

**Comment by eoinell** [comment]
- yes. I've also tried the other ways of launching the h5browser (open_browser_cmd, and several different files through [datafile].show_gui()

-PyQt5 in both.

-Yes, exactly.

**Comment by YagoDel** [comment]
Give it a try now. Should be fixed

**Comment by eoinell** [comment]
That did it!
