### ISSUE TITLE
ViewBox of graphs in preview_widget of Camera base class extends beyond widget edges.

### ISSUE THREAD

**Issue by eoinell** [nanophotonics/nplab#97]
This occurs in python 2 and 3, but _only_ on the **python3** branch. 

The example I've seen is using the Andor:
When you take a single-track spectrum, the x-axis extends beyond the edges of the widget such that it's no longer possible to see the values on the y-axis.

It seems to be in here:
https://github.com/nanophotonics/nplab/blob/1acbb60874e39e2b540e25a2c152ebb049dc227c/nplab/instrument/camera/camera_scaled_roi.py#L215

It doesn't do so when taking an image however.

**Comment by YagoDel** [comment]
Screenshot please 🙇

**Comment by eoinell** [comment]
![image](https://user-images.githubusercontent.com/43847943/70897034-c3245280-1fe9-11ea-9b4e-795fc073df26.png)
![image](https://user-images.githubusercontent.com/43847943/70897078-dafbd680-1fe9-11ea-8c1f-23401ff56d6d.png)
![image](https://user-images.githubusercontent.com/43847943/70897393-68d7c180-1fea-11ea-871f-c2465e4a94d5.png)
![image](https://user-images.githubusercontent.com/43847943/70897429-81e07280-1fea-11ea-995d-0e926b34a7b9.png)

Each is a before/after image pair of clicking capture in single track mode. (the 1st gui hasn't set the x_axis)

**Comment by eoinell** [comment]
I made a dummy class just there of CamerScaledRoi which replicates the issue; it works in master but not in python3

**Comment by eoinell** [comment]
Side-by-side:
![image](https://user-images.githubusercontent.com/43847943/70916911-4eb2d900-2014-11ea-9a64-5ff9cb47ab03.png)

**Comment by YagoDel** [comment]
For anyone looking at this, the fix is [line 204](https://github.com/nanophotonics/nplab/blob/25713c882112a3d0a765b00c9d4e5bad6d95df7a/nplab/instrument/camera/camera_scaled_roi.py#L204) in 25713c882112a3d0a765b00c9d4e5bad6d95df7a
